module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    CART_COLLECTION:'cart',
    CATEGORY_COLLECTION:'category',
    ORDER_COLLECTION:'ORDER',
    ADDRESS_COLLECTION:'address',
    WALLET_COLLECTION:'wallet',
    COUPON_COLLECTION:'coupon',
}